version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9444:8080" # Map external port 9444 to Jenkins internal port 8080
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent storage for Jenkins data
    networks:
      - jenkins_ansible_network

  jenkins_agent:
    image: jenkins/inbound-agent
    environment:
      - JENKINS_URL=http://jenkins:8080/jenkins
      - JENKINS_SECRET=<your-agent-secret>
      - JENKINS_AGENT_NAME=agent-${HOSTNAME}
    networks:
      - jenkins_ansible_network
    deploy:
      replicas: 3

networks:
  jenkins_ansible_network:
    driver: bridge

volumes:
  jenkins_home:
